import { NextResponse } from "next/server";

export async function POST(request: Request) {
  try {
    const { content, title, format } = await request.json();

    if (!content || !title) {
      return NextResponse.json({ error: "Content and title required" }, { status: 400 });
    }

    if (format === "txt") {
      // Plain text — strip markdown symbols
      const plain = content
        .replace(/^#{1,6}\s+/gm, "")
        .replace(/\*\*/g, "")
        .replace(/\*/g, "")
        .replace(/`/g, "")
        .replace(/\|/g, " | ")
        .replace(/^-{3,}$/gm, "─".repeat(60))
        .trim();

      const withHeader = `${title.toUpperCase()}\n${"─".repeat(60)}\nGenerated by The BA Portal — Intelligence Engine\nDate: ${new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })}\n${"─".repeat(60)}\n\n${plain}`;

      return new Response(withHeader, {
        headers: {
          "Content-Type": "text/plain;charset=utf-8",
          "Content-Disposition": `attachment; filename="${title.toLowerCase().replace(/\s+/g, "-")}.txt"`,
        },
      });
    }

    if (format === "docx") {
      const { Document, Packer, Paragraph, TextRun, HeadingLevel, Table, TableRow, TableCell, BorderStyle, WidthType, AlignmentType } = await import("docx");

      const lines = content.split("\n");
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const docChildren: any[] = [];

      // Header
      docChildren.push(
        new Paragraph({
          text: title,
          heading: HeadingLevel.TITLE,
          spacing: { after: 200 },
        }),
        new Paragraph({
          children: [
            new TextRun({ text: "Generated by The BA Portal — Intelligence Engine  ", color: "808080", size: 18 }),
            new TextRun({ text: new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" }), color: "808080", size: 18 }),
          ],
          spacing: { after: 400 },
        })
      );

      // Parse table
      let i = 0;
      while (i < lines.length) {
        const line = lines[i].trim();

        if (line.startsWith("# ") || line.startsWith("## ") || line.startsWith("### ")) {
          const level = line.startsWith("### ") ? HeadingLevel.HEADING_3 : line.startsWith("## ") ? HeadingLevel.HEADING_2 : HeadingLevel.HEADING_1;
          const text = line.replace(/^#{1,3}\s+/, "").replace(/\*\*/g, "");
          docChildren.push(new Paragraph({ text, heading: level, spacing: { before: 300, after: 120 } }));
          i++;
        } else if (line.startsWith("|") && i + 1 < lines.length && lines[i + 1].trim().startsWith("|")) {
          // Table — collect all rows
          const tableLines: string[] = [];
          while (i < lines.length && lines[i].trim().startsWith("|")) {
            if (!lines[i].includes("---")) tableLines.push(lines[i].trim());
            i++;
          }
          if (tableLines.length > 0) {
            const rows = tableLines.map(r => r.split("|").filter(c => c.trim()).map(c => c.trim().replace(/\*\*/g, "")));
            const headerRow = rows[0];
            const dataRows = rows.slice(1);

            const tableRows = [
              new TableRow({
                tableHeader: true,
                children: headerRow.map(cell =>
                  new TableCell({
                    children: [new Paragraph({ children: [new TextRun({ text: cell, bold: true, size: 18 })] })],
                    shading: { fill: "E8F5F2" },
                  })
                ),
              }),
              ...dataRows.map(row =>
                new TableRow({
                  children: row.map(cell =>
                    new TableCell({
                      children: [new Paragraph({ children: [new TextRun({ text: cell, size: 18 })] })],
                    })
                  ),
                })
              ),
            ];

            docChildren.push(
              new Table({
                rows: tableRows,
                width: { size: 100, type: WidthType.PERCENTAGE },
              })
            );
            docChildren.push(new Paragraph({ text: "", spacing: { after: 200 } }));
          }
        } else if (line.startsWith("- ") || line.startsWith("* ")) {
          docChildren.push(new Paragraph({
            text: line.slice(2).replace(/\*\*/g, ""),
            bullet: { level: 0 },
            spacing: { after: 60 },
          }));
          i++;
        } else if (/^\d+\.\s/.test(line)) {
          docChildren.push(new Paragraph({
            text: line.replace(/^\d+\.\s/, "").replace(/\*\*/g, ""),
            numbering: { reference: "default-numbering", level: 0 },
            spacing: { after: 60 },
          }));
          i++;
        } else if (line === "" || line === "---") {
          docChildren.push(new Paragraph({ text: "", spacing: { after: 100 } }));
          i++;
        } else if (line) {
          docChildren.push(new Paragraph({
            children: [new TextRun({ text: line.replace(/\*\*/g, ""), size: 22 })],
            spacing: { after: 120 },
          }));
          i++;
        } else {
          i++;
        }
      }

      const doc = new Document({
        numbering: {
          config: [{
            reference: "default-numbering",
            levels: [{ level: 0, format: "decimal", text: "%1.", alignment: AlignmentType.LEFT }],
          }],
        },
        sections: [{
          properties: {},
          children: docChildren,
        }],
      });

      const buffer = await Packer.toBuffer(doc);

      return new Response(buffer as unknown as BodyInit, {
        headers: {
          "Content-Type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
          "Content-Disposition": `attachment; filename="${title.toLowerCase().replace(/\s+/g, "-")}.docx"`,
        },
      });
    }

    return NextResponse.json({ error: "Invalid format. Use txt or docx." }, { status: 400 });

  } catch (error) {
    console.error("Export error:", error);
    return NextResponse.json({ error: "Export failed. Please try again." }, { status: 500 });
  }
}
